# -*- coding: utf-8 -*-
"""Crypto_coinRNN.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1PMPMtwhl4eJ_gjHGKPB82fHtfXgm_qLo
"""

import tensorflow as tf
import numpy as np
import requests # 웹으로 요청 할때 사용하는 라이브러리
import matplotlib.pyplot as plt
import os
import pickle
import random
random.seed(111)
np.random.seed(111)
tf.random.set_seed(111)

#config
receive_count=1001
time_step = 90
coin_name="BTC"
RPATH = "./"
rob_scaler=None
target_list = ["opening_price","high_price","low_price","trade_price",\
               "prev_closing_price","change_rate"]

### 1. 데이터 수신 함수 정의부

def get_day_candle(count,coin_name="BTC"):# get_day_candle(수신할 데이터 수량)
  #오늘 날짜
  #print(datetime.now().strftime("%Y-%m-%d %H:%M:%S")) #2026-02-06 01:11:28.126344
  cur_time = datetime.now()
  #date_str = "2026-02-06 00:00:01"#"yyyy-MM-dd HH:mm:ss"
  date_str=""
  time_cnt = receive_count//200
  if receive_count%200:
    time_cnt+=1
  ret_datas = []
  for c in range(time_cnt):
    date_str = cur_time.strftime("%Y-%m-%d %H:%M:%S")
    #7-21 '2025-07-22T00:00:00',  '2025-01-03T00:00:00'
    #2-6 '2026-02-06T00:00:00      '2025-07-21T00:00:00'
    # print("pre ",cur_time)
    cur_time = cur_time-timedelta(days=200)
    # print("aft ",cur_time)
    DAY_CANDLE = r"https://api.bithumb.com/v1/candles/days?market=KRW-{}&count={}&to={}"\
    .format(coin_name,count,date_str)
    receive_data = (requests.get(DAY_CANDLE).json())
    receive_data.reverse()#시간 순서 오름차순으로 뒤집기
    ret_datas = receive_data+ret_datas
  return ret_datas #[{},{},{},.......]

### 2. 데이터 분석(상관성, 타입, 크기, 이상치, 결측치 ....)
###   분석후 결과 인덱스만 추출
def extract_data(raw_datas):
  global target_list
  conv_datas=[]
  for unit in raw_datas:
    temp=[]
    for key in unit:
      if key in target_list:
        temp.append(unit[key])
    if temp:
      conv_datas.append(temp)
  print(len(conv_datas))
  return conv_datas

### 3. robust(비이상치 데이터가 존재) 스케일링
###### 주의사항 2차원 이하의 데이터를 주입해야함
import sklearn
#훈련일때는 service 파라미터를 False 로 설정
def scale_data(tar_datas,service=True):#data shape (수량,6)
  global RPATH
  global rob_scaler
  print("데이터모양",tar_datas.shape)
  if (not service) and (not rob_scaler):
    rob_scaler = sklearn.preprocessing.RobustScaler()
    convt_datas = rob_scaler.fit_transform(tar_datas)
    print("0번필드 4분위법 평균:",convt_datas[:,0].mean())
    print("0번필드 4분위법 편차:",convt_datas[:,0].std())
    print("-1번필드 4분위법 평균:",convt_datas[:,-1].mean())
    print("-1번필드 4분위법 편차:",convt_datas[:,-1].std())
  #디렉토리 생성
    if not os.path.exists(RPATH+"config/"):
      os.makedirs(RPATH+"config/")
    with open(RPATH+"config/"+coin_name+"_rbs.pre","wb") as fp:
      pickle.dump(rob_scaler,fp)
  else:
    #훈련이 아닐때는 rob_scaler 값이 변경되면 안됩니다.
    if (not rob_scaler) and os.path.exists(RPATH+"config/"+coin_name+"_rbs.pre"):
      with open(RPATH+"config/"+coin_name+"_rbs.pre","rb") as fp:
        rob_scaler=pickle.load(fp)
        convt_datas = rob_scaler.transform(tar_datas)
  #객체 저장
  return convt_datas

### 4. 정규화 복원
def convt_data(tar_ydatas):#복원대상 필드 [0] : 현재가부분
  global rob_scaler
  if (not rob_scaler) and os.path.exists(RPATH+"config/"+coin_name+"_rbs.pre"):
    with open(RPATH+"config/"+coin_name+"_rbs.pre","rb") as fp:
      rob_scaler=pickle.load(fp)
  ret_data = rob_scaler.inverse_transform(tar_ydatas)
  return ret_data

### 5. 시계열 데이터 생성( 타임 스텝별 )
def create_rnn_data(raw_datas):
  global time_step
  x_datas = []
  y_datas = []
  for i in range(len(raw_datas)-time_step):
    x_datas.append(raw_datas[i:i+time_step])
    y_datas.append(raw_datas[i+time_step])

  return np.array(x_datas),np.array(y_datas)

### 6. 모델의 구성
###   - 과대적합 그래프로 모델의 파라미터를 줄이고 dropout을 50% 이상 증진함

from tensorflow.keras import Sequential,Input
from tensorflow.keras.layers import Dense,LSTM,Dropout,BatchNormalization
def train_model():
  global time_step;global target_list
  model = Sequential()
  model.add(Input((time_step,len(target_list))))
  lstm_1 = tf.keras.layers.LSTM(
        16,
        activation='tanh',
        recurrent_activation='sigmoid',
        return_sequences=True)
  lstm_2 = tf.keras.layers.LSTM(
        8,
        activation='tanh',
        recurrent_activation='sigmoid',
        return_sequences=False)
  model.add(lstm_1)
  model.add(lstm_2)
  model.add(Dense(64,activation="relu"))
  #model.add(BatchNormalization()) 과대적합의 원인
  model.add(Dropout(0.3))
  model.add(Dense(32,activation="relu"))
  model.add(Dropout(0.3))
  model.add(Dense(len(target_list),activation="linear"))
  model.compile(loss="mse",optimizer=tf.keras.optimizers.Adam(1.2e-3),metrics=["mae"])
  return model
#L2 규제 - 가중치 제한 하는 기법
# Dense(
#     64,
#     activation='relu',
#     kernel_regularizer=regularizers.L2(1e-4)
# )

### 7. 훈련실행
def runn_train(model,x_train,y_train,epochs):
  early_obj = tf.keras.callbacks.EarlyStopping(
    monitor='val_loss',# 모니터링할 수치
    min_delta=0,# 떨어지는 값의 차이값 기준
    patience=10,# 최소수치에서 기다리는 횟수
    verbose=1,
    mode='auto',#자동 loss 더 낮은값을 체크하고 acc 더 높은 값을 체크
    restore_best_weights=False,# 조기종료시 최적의 값의 가중치로 복원
    start_from_epoch=0 #조기종료 체크 시점
)

  return model.fit(x_train,y_train,epochs=epochs,\
                   shuffle=False,\
                   validation_data=(x_train,y_train),\
                   batch_size=len(x_train)//5,callbacks=[early_obj])

### 8. 훈련결과 시각화 그래프
def rander_graph(res):
  print("xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx")
  print(res.history.keys())
  direction_acc = np.mean(
    np.sign(np.diff(res.history["loss"][-200:])) == np.sign(np.diff(res.history["val_loss"][-200:]))
  )
  print("방향성 정확도:",direction_acc)
  #dict_keys(['loss', 'mae', 'val_loss', 'val_mae'])
  plt.subplot(2,2,1)
  plt.plot(res.history["loss"],label="train_loss")
  plt.plot(res.history["val_loss"],label="valid_loss")
  plt.legend()
  plt.title("LOSSES")
  plt.xlabel(f"direction_acc: {direction_acc*100:.4f}%")
  plt.subplot(2,2,2)
  plt.plot(res.history["mae"],label="train_mae")
  plt.plot(res.history["val_mae"],label="valid_mae")
  plt.legend()
  plt.title("MAE")
  if not os.path.exists(r"{}/chart".format(RPATH)):
    os.makedirs(r"{}/chart".format(RPATH))
  plt.savefig(r"{}/chart/{}_mse_mae.png".format(RPATH,coin_name))
  plt.show()

# 9. 모델과 환경 저장
#
def dump_model(model):
  model.save(f"{coin_name}_{time_step}_lstm.keras")
  model.save_weights(f"{coin_name}_{time_step}_lstm.weights.h5")

from datetime import datetime, timedelta
if __name__=="__main__":
  #1.1 수신함수 실행부
  ret = get_day_candle(receive_count)
  #'candle_date_time_kst': '2025-07-22T00:00:00'
  #'candle_date_time_kst': '2026-02-06T00:00:00'
  #파일로 저장하는 방법
  # data_text = " ".join(map(str,ret))
  # with open("./datas.txt","w") as fp:
  #    fp.write(data_text)
  #1.2 수신 데이터 검증
  print(len(ret))
  print(ret[198])
  print(ret[199])
  print(ret[200])
  print(ret[201])
  print("============")
  print(ret[-202])
  print(ret[-201])
  print(ret[-200])
  print(ret[-199])
  print(ret[-198])
  print(ret[-1])
  # 2.1 상관데이터 추출
  ext_data = np.array(extract_data(ret))
  print(ext_data.shape)
  print("가격복원 검증(raw):",ext_data[-1])
  # 3.1 데이터 전처리
  comp_datas = scale_data(ext_data,service=False)#(data)

  # 5.1 시계열 데이터 생성
  x_datas,y_datas = create_rnn_data(comp_datas)
  print(x_datas.shape)
  print(y_datas.shape)
  # 4.1 정규화 복원
  print(convt_data(np.array([y_datas[-1]])))
  struct_model=train_model()
  # 6.1 모델 생성
  model = train_model()
  # 7.1 훈련실행
  res = runn_train(model,x_datas,y_datas,1000)
  #8.1 훈련결과 그래프 출력
  rander_graph(res)
  model.summary()

#모델 저장
dump_model(model)

